#!/usr/bin/env ruby

# INEGI
# Encuesta Nacional de Ingresos y Gastos de los Hogares (ENIGH). 2018 Nueva serie.
# https://www.inegi.org.mx/programas/enigh/nc/2018/#Microdatos

require_relative 'lib/csv'
require_relative 'lib/inequality'

def title(text)
  puts [nil, text, '-' * text.size]
end

def print_quantiles(quantiles, probs)
  quantiles.each_with_index do |e, i|
    puts '%02i%% %.00f' % [100 * probs[i], e]
  end
end

TOP_TEN = gen_probs(10, from=0.9)

$income = csv('concentradohogar.csv', %w[ing_cor factor], :to_i).to_a

$quantiles = wquantiles($income, DECILES)
$median = $quantiles[4]

title 'General'
puts 'Median: %0.f' % [$median]
puts 'Gini: %.02f%%' % [100 * gini($income)]

title 'Classes'
puts 'Middle: %0.f < x < %0.f' % [$median * 0.75, $median * 2.0]

title 'Deciles'
print_quantiles($quantiles, DECILES)

title 'Top 10%'
print_quantiles(wquantiles($income, TOP_TEN), TOP_TEN)
