#!/usr/bin/env ruby

# INEGI
# Encuesta Nacional de Ingresos y Gastos de los Hogares (ENIGH). 2018 Nueva serie.
# https://www.inegi.org.mx/programas/enigh/nc/2018/#Microdatos

require_relative 'lib/csv'
require_relative 'lib/inequality'

def convert(v)
  v /= 17.00 # USDMXN
  v /= (124.912 / 128.832) # CPI: Aug-Nov 2022 -> Jul 2023
  v * 4 # data is by quarter
end

def title(text)
  puts [nil, text, '-' * text.size]
end

def print_quantiles(quantiles, probs)
  quantiles.each_with_index do |e, i|
    puts '%02i%% %.00f' % [100 * probs[i], convert(e)]
  end
end

TOP_TEN = gen_probs(10, from=0.9)

$income = csv('data/concentradohogar.csv', %w[ing_cor factor], :to_i).to_a

$quantiles = wquantiles($income, DECILES)
$median = $quantiles[4]

title 'General'
puts 'Median: %0.f' % [convert($median)]
puts 'Gini: %.02f%%' % [100 * gini($income)]

title 'Classes'
puts 'Middle: %0.f < x < %0.f' % [convert($median * 0.75), convert($median * 2.0)]

title 'Deciles'
print_quantiles($quantiles, DECILES)

title 'Top 10%'
print_quantiles(wquantiles($income, TOP_TEN), TOP_TEN)
